language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
- pip install pytest
script:
- "./runtests.sh"
deploy:
  provider: pypi
  user: GusBricker
  password:
    secure: Z5wHM4ouusAC3xhABBjyCagzZ+hvXUhP6EgzCab87uBjXPYuDeE/hI78/OjCC9D66xeSiBCODa0vO8LKRj9fThvDOVuGOGlc3MpgPKpsnK3L+mxWeeGxb/SA1atGssD2BzWcm+LS3NVh4E+b11wUnLBhi3CR79adun9GRDFjkHyk1ZL01ZpYp1O/ukUiO3ga0Q9mFS+9+r08qsvldtD8Xuw70IOf4MdflXSq6BwdqF4sWPYtDbsLMKhfPWC1hTSja2FjFPL5fvI+LGn5lSoJqE3IKuO7q8Hf0zVKciHRGfkKujh6+Vc51i9lAU2565SY+LHVn5gD2hiMBSpIjGLgRyCurZ6W7e2H03EcnYPxPoNSz3QWUBIv4z7QB2xN+jvkO2Kye8tTvUtOKAFydXWfLJsnzzBO+OYLvsoaAufP2OPbJEpXZZWoWXNiWb4TF7lbqeBpaOGJUDG0/qd0EQJr+N8OIa59aCjc4cud8GFm1zgiF70U+BAZ382x1r3Q2rNJm/CXWsoMQuAh2garfkzP65qW5ZR5TpIROiDsB7wHGMaCSZ3TGBRny703FfFugsOFRaWrWBf3aUbquCz9/X+k6ny5nVinOXYNEO4Hq+Wz8WEB28H6ZqiBsFjB/4XetOysU99OsNA8LBGU0QU8pnCGtUU26qZWnsu/lVad+rvlgGs=
  on:
    tags: true
    repo: GusBricker/dynamo-store
    python: '3.6'
  distributions: sdist bdist_wheel
env:
  global:
  - secure: nZyjK7afyED1+SvYu7jimyiuPXUt9wFL2O25c7T6N6qVxx6n2phVyMDUbeilmcVX1Mw+/C+BfLhymHv+L+50CR1rpyL93pZ6gKRUTDLxiK3ZlTBKTjQPzEF1ewak/RBNHD0vE7i5G4jmeW/3LzyYn0VaAEYqxWc14a4uc5HD6L1QEqXEy+TSjnWapZ4x3Q5r5BVZrtXEjA5vr5eoBl7mGRam3Cau9Cc0EV+31OjeHVbCwcSwZxN+S9Qtc8M6lpcYhPpE+Ocwr/G4So4YcoB65luIvJQnhMs7bwN9eCme7TfF49r+hqY9yMsRq3yEsXJEIA9EjvLS01XBUhMNNlQ0G1rygAhPYAtpAO8MIrBB8/ySYJEKmJS3pgRL+Ibee6JiQlI89rb0RB3VHTwsMRYA6X2pUxtqpGP+UYavFLNiAgVPdA3GPHiHzidNUzKlG+KAOHU0zmfy/kxdj8xKrkXep4xGmZWKkfTaM3zyiIFykeS29YzkyMaIkfOCKlD+gcGsHZE0ZWrQv8bCAh/1O/uA8+ViIqNA01y7UWq2i3BrJEgdQ/k/gCRoez3jFMNrW0nDWQp6UqRXwD/n5v+4KP4zh6/81c5FbQaVVA0w5S0wJw/djepY33CTIEz/2gVtkQbYC2DiY87QeU3ttfthszAABYLVswTmIuI5+dHmR4dkIIU=
  - secure: blXN2K3PXCl1KcpRVoQS/IVM2efXWHvl9AyDQNeiQVFHVlUpSwrn2lUAUaMWM+oo2X0365uahMWH21Z5E7sykinUDmvhaMpaWr6HgzCpEerRO/5qyRw0rwzYKYyZSmWbXlIu4kSt//uPdJewHtlEdZkhky4COB0enLzrTT/xbvo3oSJXjDUQmrOLSbLvLk2ZrN/CVi4Kqugdi/tpoLI6g5SL4BNgoqOQ6hCoLHKlPMPtIv5lX4QyYWz6cnT6c1zMiMDDHifBjduOJvJuPTgNPqXThF3yBj16gnlsQoh3N0EPhHr/w6mI/5ezF2em2ZJ+sPEP3iCvOiOkpwOjayiN8StehUj8Dc23zHXhgWtvaQE3rlC6pCyA0gZjGAS5miuBD2BIwjI+lyi57coXOGuiDSFC8kLF/iLn6LFPnMACAyPUdoZL2dPfxWD2+ni06taDhvfO8uHmFluHUYYRJOUPptA33WvrEK3PO4pqrkt/dtO7k+l4YcNH1d4Mf1Mo4/SQHt6KHw8CkM/L2DXn3Cq4r+CnR/q4kx14LNVst1GhHbXDdO4RYW8HCLrp1QWDJpjz9hvomGtb3shrCIEdc/RvvRsybQADCzZ5I50YmdqQF/g9lPbxlro82DUS8xee0pno1UGESdtOlkUDE6SQL6cvnro5ewx0TuF6aEdM2+G+kHM=
